global:
  # We can use one Slack webhook url to send to different channels!
  slack_api_url: "https://hooks.slack.com/services/token"

# The directory from which notification templates are read.
templates:
  - "/etc/alertmanager/template/*.tmpl"

# The root route on which each incoming alert enters.
route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h

  group_by: [alertname, job]

  # A default receiver
  receiver: "warning-channel"

  # custom routes
  routes:
    - match:
        severity: critical
      receiver: critical-channels

receivers:
  - name: "warning-channel"
    slack_configs:
      - channel: "ops-warning-prod"
        api_url: "https://hooks.slack.com/services/token"
        username: "Prometheus"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] Prometheus Alert Notification"
        text: >-
          <!channel>
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            {{ .Annotations.description }}
          {{ end }}

  # Send critical alerts to TW and Daimler channels
  - name: "critical-channels"
    slack_configs:
      # Slack Channel
      - api_url: "https://hooks.slack.com/services/token"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] Prometheus Alert Notification"
        text: >-
          <!channel>
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
            {{ .Annotations.description }}
          {{ end }}
