---
- name: ensure the promtheus dir
  file: path={{ prometheus_dir }} state=directory mode=0755

- name: ensure the promtheus data dir
  file: path={{ prometheus_data_path }} state=directory mode=0755

- name: download prometheus package
  unarchive: src="files/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz" dest="/tmp"

- name: copy the prometheus to dir
  copy: src=/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus dest={{ prometheus_dir }}/prometheus mode="a+x" remote_src=yes

- name: copy the prometool to dir
  copy: src=/tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool dest={{ prometheus_dir }}/promtool mode="a+x" remote_src=yes

- name: add prometheus config file
  template: src=prometheus.yml.j2 dest={{ prometheus_config_file }}
  notify: restart prometheus

- name: create prometheus systemd file
  template: src=prometheus.service.j2 dest=/etc/systemd/system/prometheus.service
  notify: restart prometheus
